### ISSUE TITLE
请问这是怎么回事

### ISSUE THREAD

**Issue by lwgpshit** [KevinOfNeu/hexo-theme-xxoo#11]
Unhandled rejection ReferenceError: C:\Users\ttt\Desktop\HEXXX\themes\xoxo\layout\post.ejs:28
    26|     </span>
    27|       <span class="slash">/</span>
 >> 28|       <span class="read">阅读耗时 <%=readingTime(page.content, '分钟') %></span>
    29|     </header>
    30|
    31|     <div class="post-content">

readingTime is not defined
    at eval (C:\Users\ttt\Desktop\HEXXX\themes\xoxo\layout\post.ejs:32:7)
    at post (D:\网站\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (D:\网站\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (D:\网站\node_modules\hexo\lib\theme\view.js:41:15)
    at D:\网站\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (D:\网站\node_modules\bluebird\js\release\util.js:16:23)
    at D:\网站\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\网站\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:459:10)
    at resume_ (_stream_readable.js:948:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

点阅读全文的时候出现的

**Comment by Holdge** [comment]
> Unhandled rejection ReferenceError: C:\Users\ttt\Desktop\HEXXX\themes\xoxo\layout\post.ejs:28
> 26|
> 27| /
> 
> > > 28|       阅读耗时 <%=readingTime(page.content, '分钟') %>
> > > 29|     
> > > 30|
> > > 31|
> 
> readingTime is not defined
> at eval (C:\Users\ttt\Desktop\HEXXX\themes\xoxo\layout\post.ejs:32:7)
> at post (D:\网站\node_modules\ejs\lib\ejs.js:682:17)
> at viewFn._compiled (D:\网站\node_modules\hexo\lib\theme\view.js:136:48)
> at viewFn.View.render (D:\网站\node_modules\hexo\lib\theme\view.js:41:15)
> at D:\网站\node_modules\hexo\lib\hexo\index.js:61:21
> at tryCatcher (D:\网站\node_modules\bluebird\js\release\util.js:16:23)
> at D:\网站\node_modules\bluebird\js\release\method.js:15:34
> at RouteStream._read (D:\网站\node_modules\hexo\lib\hexo\router.js:126:3)
> at RouteStream.Readable.read (_stream_readable.js:459:10) at resume_ (_stream_readable.js:948:12)
> at processTicksAndRejections (internal/process/task_queues.js:84:21)
> 
> 点阅读全文的时候出现的

readingTime 安装一下依赖
